# -*- coding: utf-8 -*-
"""Homework8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMJBIZgb19U1z6LwxKyUArsHUToCuvKP
"""

import numpy as np
import matplotlib.pyplot as plt

def make_sine_wave(x, A, w):
    """Return a sine wave with amplitude A and angular frequency w."""
    return A * np.sin(w * x)

# Create x from 0 to 2π with 1000 points
x = np.linspace(0, 2 * np.pi, 1000)

# Amplitudes and frequencies
amplitudes = [0.5, 1, 1.5, 2, 2.5]
frequencies = [1, 2, 3, 4, 5]

# Create a figure
plt.figure(figsize=(10, 6))

# Plot sine waves
line_styles = ['-', '--', '-.', ':', (0, (3, 5, 1, 5))]  # bonus: different line styles
for A, w, style in zip(amplitudes, frequencies, line_styles):
    y = make_sine_wave(x, A, w)
    plt.plot(x, y, linestyle=style, label=f"A={A}, w={w}")

# Add labels and legend
plt.title("Sine Waves with Varying Amplitudes and Frequencies")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()

import pandas as pd

# Load CSV
df = pd.read_csv("stars.csv")

# Print first 5 rows
print(df.head())

# Print shape and column info
print(f"\nShape: {df.shape}")
print("\nColumn names and data types:\n", df.dtypes)

import seaborn as sns

# Load the penguins dataset
penguins = sns.load_dataset("penguins")
print(penguins.head())

# Create subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Scatter plot
sns.scatterplot(data=penguins, x="flipper_length_mm", y="body_mass_g", hue="species", ax=ax1)
ax1.set_title("Flipper Length vs Body Mass")
ax1.set_xlabel("Flipper Length (mm)")
ax1.set_ylabel("Body Mass (g)")
ax1.legend()

# Histogram
sns.histplot(data=penguins, x="body_mass_g", kde=True, ax=ax2, color="orange")
ax2.set_title("Distribution of Body Mass")
ax2.set_xlabel("Body Mass (g)")
ax2.set_ylabel("Count")

plt.tight_layout()
plt.show()